on:
  pull_request:

  push:
    branches:
      - main


name: Linters

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: "get patched lib"
        run: "cd ../ && git clone --depth 1 https://github.com/tazz4843/deepspeech-rs/ && cd deepspeech-rs && git submodule init && git submodule update --depth 1 && cd ../scripty"

      - run: rustup component add rustfmt

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: "install ld"
        run: "sudo apt install lld -y"

      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
          override: true

      - name: "get patched lib"
        run: "cd ../ && git clone --depth 1 https://github.com/tazz4843/deepspeech-rs/ && cd deepspeech-rs && git submodule init && git submodule update --depth 1 && cd ../scripty"

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
          name: Clippy Output
